         real(kind=8)   amp_r, xc_r, yc_r, zc_r, sig_r
         real(kind=8)   amp_i, xc_i, yc_i, zc_i, sig_i
         real(kind=8)   amp  , xc  , yc  , zc  , sig  
         real(kind=8)   kgmass, x,y,z, cpi
      parameter ( amp_r =  0.1d0 )
      parameter ( xc_r  = -0.0d0 )
      parameter ( yc_r  =  0.0d0 )
      parameter ( zc_r  =  0.0d0 )
      parameter ( sig_r =  0.5d0 )
      !
      parameter ( amp_i =  0.1d0 )
      parameter ( xc_i  = +0.0d0 )
      parameter ( yc_i  =  0.0d0 )
      parameter ( zc_i  =  0.0d0 )
      parameter ( sig_i =  0.5d0 )
      !
      parameter ( amp   =  0.2d0 )
      parameter ( xc    =  0.0d0 )
      parameter ( yc    =  0.0d0 )
      parameter ( zc    =  0.0d0 )
      parameter ( sig   =  0.5d0 )
      !
      parameter ( kgmass=  1.0d0 )
      parameter ( cpi  =  3.14159265d0 )
