#!/usr/bin/perl

$bsfrac_stop=2.0e-15;
$execute="runmpi";

$Pgname = `basename $0`; chop $Pgname;
$Usage  = "usage: $Pgname\n";

$Ltrace = 0;

sub usage {
	print "$Usage";
	exit;
}

sub err2 {
	local($mess,$rest) = @_;
	print STDERR "$Pgname: $mess\n";
}

sub ltrace {
	local($mess,$rest) = @_;
	print STDERR "$mess\n" if $Ltrace;
}

$bsfrac=`bsfrac`; chop $bsfrac; $bsfrac=-$bsfrac unless $bsfrac > 0;

printf "$pgname: Beginning search with <bsfrac>=$bsfrac ($bsfrac_stop)\n";
while( $bsfrac > $bsfrac_stop ) {
	$bscurr=`bscurr`; chop $bscurr;
	$rc=`/bin/rm TX`;
   printf "$pgname: Running: $execute $bscurr \n";
   $rc=`date >> mysearch.timings`;
   $rc=`echo Running >> mysearch.timings`;
	$rc=system("$execute $bscurr");
   $rc=`date >> mysearch.timings`;
   $junk=`tail -1 Exitstatus`;
   if ($junk =~ "Out of memory") {
		printf "$pgname: Ran out of memory, quitting.\n";
		exit;
   }
	if( -f "TX" ) {
		printf "$pgname: Flagged as collapsing texture.\n";
		$rc=system("bshi");
	} else {
		printf "$pgname: Flagged as dispersing texture.\n";
		$rc=system("bslo");
	}
	$bsfrac=`bsfrac`; chop $bsfrac; $bsfrac=-$bsfrac unless $bsfrac > 0;
	printf "$pgname: Continuing search with <bsfrac>=$bsfrac ($bsfrac_stop)\n";
}
