#!/bin/sh

CODE=nlsm
ID=id
NUMPROCS=2



Usage() {
cat<<END
   Runs nlsm with same "amp" and "amp2"
   usage: run2mpi <amplitude value>
END
exit 1
}

case $# in 
1) A1=$1;;
*) Usage;;
esac

AMP=$A1
AMP2=$A1

setparid $ID amp  $AMP
setparid $ID amp2 $AMP2


mpirun -np $NUMPROCS $CODE $ID
