#!/bin/sh

CODE=nlsm
ID=id


A1=0.5


Usage() {
cat<<END
Runs nlsm rescaling both "amp" and "amp2"
usage: run <relative amplitude value>
END
exit 1
}

case $# in 
1) rel=$1;;
*) Usage;;
esac

AMP=` echo $rel $A1 | nf "_1*_2"`
AMP2=`echo $rel $A1 | nf "_1"`

setparid $ID amp  $AMP
setparid $ID amp2 $AMP2


$CODE $ID
