       CCTK_INT :: dx_chi, dy_chi, dz_chi, dx_Gamtx
       CCTK_INT :: dy_Gamtx, dz_Gamtx, dx_Gamty, dy_Gamty
       CCTK_INT :: dz_Gamty, dx_Gamtz, dy_Gamtz, dz_Gamtz
       CCTK_INT :: dx_trK, dy_trK, dz_trK, dx_gtxx
       CCTK_INT :: dy_gtxx, dz_gtxx, dx_gtxy, dy_gtxy
       CCTK_INT :: dz_gtxy, dx_gtxz, dy_gtxz, dz_gtxz
       CCTK_INT :: dx_gtyy, dy_gtyy, dz_gtyy, dx_gtyz
       CCTK_INT :: dy_gtyz, dz_gtyz, dx_gtzz, dy_gtzz
       CCTK_INT :: dz_gtzz, dx_Atxx, dy_Atxx, dz_Atxx
       CCTK_INT :: dx_Atxy, dy_Atxy, dz_Atxy, dx_Atxz
       CCTK_INT :: dy_Atxz, dz_Atxz, dx_Atyy, dy_Atyy
       CCTK_INT :: dz_Atyy, dx_Atyz, dy_Atyz, dz_Atyz
       CCTK_INT :: dx_Atzz, dy_Atzz, dz_Atzz, dxx_gtxx
       CCTK_INT :: dxy_gtxx, dxz_gtxx, dyy_gtxx, dyz_gtxx
       CCTK_INT :: dzz_gtxx, dxx_gtxy, dxy_gtxy, dxz_gtxy
       CCTK_INT :: dyy_gtxy, dyz_gtxy, dzz_gtxy, dxx_gtxz
       CCTK_INT :: dxy_gtxz, dxz_gtxz, dyy_gtxz, dyz_gtxz
       CCTK_INT :: dzz_gtxz, dxx_gtyy, dxy_gtyy, dxz_gtyy
       CCTK_INT :: dyy_gtyy, dyz_gtyy, dzz_gtyy, dxx_gtyz
       CCTK_INT :: dxy_gtyz, dxz_gtyz, dyy_gtyz, dyz_gtyz
       CCTK_INT :: dzz_gtyz, dxx_gtzz, dxy_gtzz, dxz_gtzz
       CCTK_INT :: dyy_gtzz, dyz_gtzz, dzz_gtzz, dxx_chi
       CCTK_INT :: dxy_chi, dxz_chi, dyy_chi, dyz_chi
       CCTK_INT :: dzz_chi
       CCTK_INT :: dx_Ex, dy_Ex, dz_Ex, dx_Ey
       CCTK_INT :: dy_Ey, dz_Ey, dx_Ez, dy_Ez
       CCTK_INT :: dz_Ez, dx_Bx, dy_Bx, dz_Bx
       CCTK_INT :: dx_By, dy_By, dz_By, dx_Bz
       CCTK_INT :: dy_Bz, dz_Bz, dx_phiR, dy_phiR
       CCTK_INT :: dz_phiR, dx_phiI, dy_phiI, dz_phiI
       CCTK_INT :: dx_piR, dy_piR, dz_piR, dx_piI
       CCTK_INT :: dy_piI, dz_piI
