      CCTK_REAL, dimension(nx,ny,nz) :: dx_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: dy_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: dz_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: dx_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: dy_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: dz_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: dx_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gby
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gby
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gby
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dy_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dy_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dz_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_By
      CCTK_REAL, dimension(nx,ny,nz) :: dy_By
      CCTK_REAL, dimension(nx,ny,nz) :: dz_By
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: dx_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dy_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dx_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dy_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dz_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dx_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dy_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dz_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dx_piI
      CCTK_REAL, dimension(nx,ny,nz) :: dy_piI
      CCTK_REAL, dimension(nx,ny,nz) :: dz_piI
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_phiI
