      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: ady_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: adz_alpha
      CCTK_REAL, dimension(nx,ny,nz) :: adx_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_shiftx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: ady_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: adz_shifty
      CCTK_REAL, dimension(nx,ny,nz) :: adx_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_shiftz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_chi
      CCTK_REAL, dimension(nx,ny,nz) :: ady_chi
      CCTK_REAL, dimension(nx,ny,nz) :: adz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_trK
      CCTK_REAL, dimension(nx,ny,nz) :: ady_trK
      CCTK_REAL, dimension(nx,ny,nz) :: adz_trK
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gbx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gby
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gby
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gby
      CCTK_REAL, dimension(nx,ny,nz) :: adx_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_gbz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: adx_By
      CCTK_REAL, dimension(nx,ny,nz) :: ady_By
      CCTK_REAL, dimension(nx,ny,nz) :: adz_By
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Phi_em
      CCTK_REAL, dimension(nx,ny,nz) :: adx_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: ady_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: adz_Psi_em
      CCTK_REAL, dimension(nx,ny,nz) :: adx_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: ady_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: adz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: adx_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: ady_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: adz_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: adx_piR
      CCTK_REAL, dimension(nx,ny,nz) :: ady_piR
      CCTK_REAL, dimension(nx,ny,nz) :: adz_piR
      CCTK_REAL, dimension(nx,ny,nz) :: adx_piI
      CCTK_REAL, dimension(nx,ny,nz) :: ady_piI
      CCTK_REAL, dimension(nx,ny,nz) :: adz_piI
