      CCTK_REAL, dimension(nx,ny,nz) :: dx_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dy_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamtx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamty
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Gamtz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dy_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dz_trK
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atxz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atyy
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atyz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Atzz
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtxx
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtxy
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtxz
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtyy
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtyz
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_gtzz
      CCTK_REAL, dimension(nx,ny,nz) :: dxx_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dxy_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dxz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dyy_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dyz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dzz_chi
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ex
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ey
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Ez
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Bx
      CCTK_REAL, dimension(nx,ny,nz) :: dx_By
      CCTK_REAL, dimension(nx,ny,nz) :: dy_By
      CCTK_REAL, dimension(nx,ny,nz) :: dz_By
      CCTK_REAL, dimension(nx,ny,nz) :: dx_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dy_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dz_Bz
      CCTK_REAL, dimension(nx,ny,nz) :: dx_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dy_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dz_phiR
      CCTK_REAL, dimension(nx,ny,nz) :: dx_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dy_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dz_phiI
      CCTK_REAL, dimension(nx,ny,nz) :: dx_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dy_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dz_piR
      CCTK_REAL, dimension(nx,ny,nz) :: dx_piI
      CCTK_REAL, dimension(nx,ny,nz) :: dy_piI
      CCTK_REAL, dimension(nx,ny,nz) :: dz_piI
