       CCTK_INT :: dx_alpha, dy_alpha, dz_alpha, dx_shiftx
       CCTK_INT :: dy_shiftx, dz_shiftx, dx_shifty, dy_shifty
       CCTK_INT :: dz_shifty, dx_shiftz, dy_shiftz, dz_shiftz
       CCTK_INT :: dx_gbx, dy_gbx, dz_gbx, dx_gby
       CCTK_INT :: dy_gby, dz_gby, dx_gbz, dy_gbz
       CCTK_INT :: dz_gbz, dx_chi, dy_chi, dz_chi
       CCTK_INT :: dx_Gamtx, dy_Gamtx, dz_Gamtx, dx_Gamty
       CCTK_INT :: dy_Gamty, dz_Gamty, dx_Gamtz, dy_Gamtz
       CCTK_INT :: dz_Gamtz, dx_trK, dy_trK, dz_trK
       CCTK_INT :: dx_gtxx, dy_gtxx, dz_gtxx, dx_gtxy
       CCTK_INT :: dy_gtxy, dz_gtxy, dx_gtxz, dy_gtxz
       CCTK_INT :: dz_gtxz, dx_gtyy, dy_gtyy, dz_gtyy
       CCTK_INT :: dx_gtyz, dy_gtyz, dz_gtyz, dx_gtzz
       CCTK_INT :: dy_gtzz, dz_gtzz, dx_Atxx, dy_Atxx
       CCTK_INT :: dz_Atxx, dx_Atxy, dy_Atxy, dz_Atxy
       CCTK_INT :: dx_Atxz, dy_Atxz, dz_Atxz, dx_Atyy
       CCTK_INT :: dy_Atyy, dz_Atyy, dx_Atyz, dy_Atyz
       CCTK_INT :: dz_Atyz, dx_Atzz, dy_Atzz, dz_Atzz
       CCTK_INT :: dxx_gtxx, dxy_gtxx, dxz_gtxx, dyy_gtxx
       CCTK_INT :: dyz_gtxx, dzz_gtxx, dxx_gtxy, dxy_gtxy
       CCTK_INT :: dxz_gtxy, dyy_gtxy, dyz_gtxy, dzz_gtxy
       CCTK_INT :: dxx_gtxz, dxy_gtxz, dxz_gtxz, dyy_gtxz
       CCTK_INT :: dyz_gtxz, dzz_gtxz, dxx_gtyy, dxy_gtyy
       CCTK_INT :: dxz_gtyy, dyy_gtyy, dyz_gtyy, dzz_gtyy
       CCTK_INT :: dxx_gtyz, dxy_gtyz, dxz_gtyz, dyy_gtyz
       CCTK_INT :: dyz_gtyz, dzz_gtyz, dxx_gtzz, dxy_gtzz
       CCTK_INT :: dxz_gtzz, dyy_gtzz, dyz_gtzz, dzz_gtzz
       CCTK_INT :: dxx_chi, dxy_chi, dxz_chi, dyy_chi
       CCTK_INT :: dyz_chi, dzz_chi, dxx_alpha, dxy_alpha
       CCTK_INT :: dxz_alpha, dyy_alpha, dyz_alpha, dzz_alpha
       CCTK_INT :: dxx_shiftx, dxy_shiftx, dxz_shiftx, dyy_shiftx
       CCTK_INT :: dyz_shiftx, dzz_shiftx, dxx_shifty, dxy_shifty
       CCTK_INT :: dxz_shifty, dyy_shifty, dyz_shifty, dzz_shifty
       CCTK_INT :: dxx_shiftz, dxy_shiftz, dxz_shiftz, dyy_shiftz
       CCTK_INT :: dyz_shiftz, dzz_shiftz
       CCTK_INT :: adx_gtxx, ady_gtxx, adz_gtxx, adx_gtxy
       CCTK_INT :: ady_gtxy, adz_gtxy, adx_gtxz, ady_gtxz
       CCTK_INT :: adz_gtxz, adx_gtyy, ady_gtyy, adz_gtyy
       CCTK_INT :: adx_gtyz, ady_gtyz, adz_gtyz, adx_gtzz
       CCTK_INT :: ady_gtzz, adz_gtzz, adx_Atxx, ady_Atxx
       CCTK_INT :: adz_Atxx, adx_Atxy, ady_Atxy, adz_Atxy
       CCTK_INT :: adx_Atxz, ady_Atxz, adz_Atxz, adx_Atyy
       CCTK_INT :: ady_Atyy, adz_Atyy, adx_Atyz, ady_Atyz
       CCTK_INT :: adz_Atyz, adx_Atzz, ady_Atzz, adz_Atzz
       CCTK_INT :: adx_alpha, ady_alpha, adz_alpha, adx_shiftx
       CCTK_INT :: ady_shiftx, adz_shiftx, adx_shifty, ady_shifty
       CCTK_INT :: adz_shifty, adx_shiftz, ady_shiftz, adz_shiftz
       CCTK_INT :: adx_chi, ady_chi, adz_chi, adx_Gamtx
       CCTK_INT :: ady_Gamtx, adz_Gamtx, adx_Gamty, ady_Gamty
       CCTK_INT :: adz_Gamty, adx_Gamtz, ady_Gamtz, adz_Gamtz
       CCTK_INT :: adx_trK, ady_trK, adz_trK, adx_gbx
       CCTK_INT :: ady_gbx, adz_gbx, adx_gby, ady_gby
       CCTK_INT :: adz_gby, adx_gbz, ady_gbz, adz_gbz
       CCTK_INT :: dx_Ex, dy_Ex, dz_Ex, dx_Ey
       CCTK_INT :: dy_Ey, dz_Ey, dx_Ez, dy_Ez
       CCTK_INT :: dz_Ez, dx_Bx, dy_Bx, dz_Bx
       CCTK_INT :: dx_By, dy_By, dz_By, dx_Bz
       CCTK_INT :: dy_Bz, dz_Bz, dx_Phi_em, dy_Phi_em
       CCTK_INT :: dz_Phi_em, dx_Psi_em, dy_Psi_em, dz_Psi_em
       CCTK_INT :: dx_phiR, dy_phiR, dz_phiR, dx_phiI
       CCTK_INT :: dy_phiI, dz_phiI, dx_piR, dy_piR
       CCTK_INT :: dz_piR, dx_piI, dy_piI, dz_piI
       CCTK_INT :: dxx_phiR, dxy_phiR, dxz_phiR, dyy_phiR
       CCTK_INT :: dyz_phiR, dzz_phiR, dxx_phiI, dxy_phiI
       CCTK_INT :: dxz_phiI, dyy_phiI, dyz_phiI, dzz_phiI
       CCTK_INT :: adx_Ex, ady_Ex, adz_Ex, adx_Ey
       CCTK_INT :: ady_Ey, adz_Ey, adx_Ez, ady_Ez
       CCTK_INT :: adz_Ez, adx_Bx, ady_Bx, adz_Bx
       CCTK_INT :: adx_By, ady_By, adz_By, adx_Bz
       CCTK_INT :: ady_Bz, adz_Bz, adx_Phi_em, ady_Phi_em
       CCTK_INT :: adz_Phi_em, adx_Psi_em, ady_Psi_em, adz_Psi_em
       CCTK_INT :: adx_phiR, ady_phiR, adz_phiR, adx_phiI
       CCTK_INT :: ady_phiI, adz_phiI, adx_piR, ady_piR
       CCTK_INT :: adz_piR, adx_piI, ady_piI, adz_piI
