
/*------------------------------------------------------------------------
 *
 *  $Id
 *  This is a machine-generated file.  Do not edit this file directly!
 *  (You can, of course, but your changes will be lost...)
 *
 *------------------------------------------------------------------------*/

#ifndef _EQS_FUNC_H
#define _EQS_FUNC_H
const int NU = 36;
const int NV = 27;
const int NW = 26;

const int UF_GT11 = 0;
const int UF_GT12 = 1;
const int UF_GT13 = 2;
const int UF_GT22 = 3;
const int UF_GT23 = 4;
const int UF_GT33 = 5;
const int UF_A11 = 6;
const int UF_A12 = 7;
const int UF_A13 = 8;
const int UF_A22 = 9;
const int UF_A23 = 10;
const int UF_A33 = 11;
const int UF_CHI = 12;
const int UF_TRK = 13;
const int UF_GAM1 = 14;
const int UF_GAM2 = 15;
const int UF_GAM3 = 16;
const int UF_ALPHA = 17;
const int UF_SHIFT1 = 18;
const int UF_SHIFT2 = 19;
const int UF_SHIFT3 = 20;
const int UF_GB1 = 21;
const int UF_GB2 = 22;
const int UF_GB3 = 23;
const int UF_EX = 24;
const int UF_EY = 25;
const int UF_EZ = 26;
const int UF_BX = 27;
const int UF_BY = 28;
const int UF_BZ = 29;
const int UF_PHI_EM = 30;
const int UF_PSI_EM = 31;
const int UF_PHIR = 32;
const int UF_PHII = 33;
const int UF_PIR = 34;
const int UF_PII = 35;

const int VF_G11 = 0;
const int VF_G12 = 1;
const int VF_G13 = 2;
const int VF_G22 = 3;
const int VF_G23 = 4;
const int VF_G33 = 5;
const int VF_SDETG = 6;
const int VF_RAD_EXP = 7;
const int VF_PSI4R = 8;
const int VF_PSI4I = 9;
const int VF_MASSADM = 10;
const int VF_MASSBONDI = 11;
const int VF_CURVATURE = 12;
const int VF_PHI2R = 13;
const int VF_PHI2I = 14;
const int VF_PHI0R = 15;
const int VF_PHI0I = 16;
const int VF_VBR_OMEGA = 17;
const int VF_VBTH_OMEGA = 18;
const int VF_CHARGE = 19;
const int VF_J1 = 20;
const int VF_J2 = 21;
const int VF_J3 = 22;
const int VF_POYNTINGX_DENS = 23;
const int VF_POYNTINGY_DENS = 24;
const int VF_POYNTINGZ_DENS = 25;
const int VF_UELL = 26;

const int WF_HAM = 0;
const int WF_MOMX = 1;
const int WF_MOMY = 2;
const int WF_MOMZ = 3;
const int WF_DIV_B = 4;
const int WF_DIV_E = 5;
const int WF_TR_A = 6;
const int WF_DETGT_M1 = 7;
const int WF_GAMTX_CON = 8;
const int WF_GAMTY_CON = 9;
const int WF_GAMTZ_CON = 10;
const int WF_CALGAMTX_CON = 11;
const int WF_CALGAMTY_CON = 12;
const int WF_CALGAMTZ_CON = 13;
const int WF_CCTK_X = 14;
const int WF_CCTK_Y = 15;
const int WF_CCTK_Z = 16;
const int WF_R = 17;
const int WF_XPHYS = 18;
const int WF_YPHYS = 19;
const int WF_ZPHYS = 20;
const int WF_MASK = 21;
const int WF_WDISS = 22;
const int WF_CHR = 23;
const int WF_ERROR = 24;
const int WF_FLAG = 25;

#endif
