#!/usr/bin/perl


# This perl script modifies files written for quad precision to double
# precision.  The gfortran compiler does not recognize quad precision.
#
#  The script changes:
#
#  (1)  real(kind=16) to real(kind=8)
#  (2)  real*16 to real*8
#  (3)  explicit quad precision numbers to double precision numbers, 
#       e.g., 1.23q45 to 1.23d45
#
#  This script is not meant to be general or handle all possible cases,
#  so it will need to be updated and fixed as new problems are encountered.

while(<>) {
  s/kind=16/kind=8/i;
  s/REAL\*16/REAL\*8/i;
  if (m/\d\.\d*q\d+/ || m/\d\.\d*q-\d+/) {
    s/(\d)\.(\d*)q(\d+)/$1\.$2d$3/;
  }

  print;
}

