
#if 0
/*------------------------------------------------------------------------
 *
 *  $Id
 *  This is a machine-generated file.  Do not edit this file directly!
 *  (You can, of course, but your changes will be lost...)
 *
 *------------------------------------------------------------------------*/
#endif
#ifndef _CCTK_H
#define _CCTK_H

#define EOS_POLY 0
#define EOS_UWM_CAND1 1
#define EOS_UWM_CAND2 2
#define EOS_UWM_CAND3 3
#define EOS_UWM_CAND6 6
#define EOS_COLD_POLY 11

#define CCTK_INT   integer
#define CCTK_REAL  real(kind=8)
#define HAVE_SDF_LIB
#define CCTK_C_PTR integer(kind=8)
#define CCTK_F77_QUAD real*16
#endif
