#!/usr/bin/perl -pi.bak

# to de-chumpify f77 code for sanity's sake when compiling with f90

  
s/character\*(\d+)/character\($1\)/;
s/real\*(\d+)/real\(kind=$1\)/;
s/integer\*(\d+)/integer\(kind=$1\)/;


