      integer gauge_type
      integer idtype
      integer evolve_geometry
      integer evolve_em_field
      integer evolve_scalar_field
      integer temperature_type
      integer read_file_alp
      integer read_file_b
      integer read_file_g
      integer read_file_k
      integer read_file_psi
      integer read_file_phir
      integer read_file_phic
      integer read_file_phim
      integer read_data_level
      integer id_d_diff_order
      real(kind=8) mr_amp
      real(kind=8) mr_shift
      real(kind=8) bamp
      real(kind=8) e1_amp
      real(kind=8) e2_amp
      integer initial_b
      real(kind=8) sf_amp
      integer initial_sf
      real(kind=8) sf_amp_axn
      real(kind=8) dil_mass
      real(kind=8) dil_alpha
      real(kind=8) dil_infty
      integer emd_bh_type
      real(kind=8) axn_mass
      real(kind=8) axn_alpha
      real(kind=8) axn_infty
      real(kind=8) sen_alpha
      real(kind=8) a_ang_par
      real(kind=8) q_elec
      real(kind=8) p_mag
      real(kind=8) bs_1_x0
      real(kind=8) bs_1_y0
      real(kind=8) bs_1_z0
      real(kind=8) bs_1_vx
      real(kind=8) bs_1_vy
      real(kind=8) bs_1_vz
      real(kind=8) bs_1_omega
      real(kind=8) bs_2_x0
      real(kind=8) bs_2_y0
      real(kind=8) bs_2_z0
      real(kind=8) bs_2_vx
      real(kind=8) bs_2_vy
      real(kind=8) bs_2_vz
      real(kind=8) bs_2_omega
      integer bh_n
      integer bh_type
      real(kind=8) bh_1_mass
      real(kind=8) bh_2_mass
      real(kind=8) bh_3_mass
      real(kind=8) bh_4_mass
      real(kind=8) bh_1_x
      real(kind=8) bh_1_y
      real(kind=8) bh_1_z
      real(kind=8) bh_2_x
      real(kind=8) bh_2_y
      real(kind=8) bh_2_z
      real(kind=8) bh_3_x
      real(kind=8) bh_3_y
      real(kind=8) bh_3_z
      real(kind=8) bh_4_x
      real(kind=8) bh_4_y
      real(kind=8) bh_4_z
      real(kind=8) bh_1_px
      real(kind=8) bh_1_py
      real(kind=8) bh_1_pz
      real(kind=8) bh_2_px
      real(kind=8) bh_2_py
      real(kind=8) bh_2_pz
      real(kind=8) bh_3_px
      real(kind=8) bh_3_py
      real(kind=8) bh_3_pz
      real(kind=8) bh_4_px
      real(kind=8) bh_4_py
      real(kind=8) bh_4_pz
      real(kind=8) bh_1_spin
      real(kind=8) bh_1_sth
      real(kind=8) bh_1_sphi
      real(kind=8) bh_2_spin
      real(kind=8) bh_2_sth
      real(kind=8) bh_2_sphi
      real(kind=8) bh_3_spin
      real(kind=8) bh_3_sth
      real(kind=8) bh_3_sphi
      real(kind=8) bh_4_spin
      real(kind=8) bh_4_sth
      real(kind=8) bh_4_sphi
      real(kind=8) outer_boundary
      real(kind=8) gr_bound_cond
      real(kind=8) fluid_bound_cond
      integer bssn_lambda_1
      integer bssn_lambda_2
      integer bssn_lambda_3
      integer bssn_lambda_4
      real(kind=8) bssn_lambda_f0
      real(kind=8) bssn_lambda_f1
      real(kind=8) bssn_lambda_f2
      real(kind=8) bssn_lambda_f3
      real(kind=8) bssn_eta_damping
      real(kind=8) bssn_R_0
      real(kind=8) bssn_eta_damping_exp
      real(kind=8) bssn_eta
      real(kind=8) bssn_trk0
      real(kind=8) bssn_kappa1
      real(kind=8) bssn_kappa2
      real(kind=8) bssn_chi_floor
      integer bssn_adv_derivs
      integer geometry_type
      integer gr_idtype
      integer mhd_idtype
      integer detgwarn
      integer force_free
      real(kind=8) q1
      real(kind=8) vinj
      real(kind=8) Kappajan
      real(kind=8) djump
      real(kind=8) rpeak
      real(kind=8) rout
      real(kind=8) stab
      real(kind=8) rho_real
      real(kind=8) magcase
      real(kind=8) kappa_max
      integer calcDivB
      integer constraints_analysis
      real(kind=8) G_scale_factor
      real(kind=8) B_scale_factor
      integer anti_aligned
      integer bfield_vacuumfreeze
      real(kind=8) bfield_taperrange
      integer project_div_B
      real(kind=8) psi_ch
      real(kind=8) psi_cr
      integer damp
      real(kind=8) id_bondi_sonic_r
      real(kind=8) id_bondi_rhoc
      real(kind=8) id_bondi_rstart
      integer id_bondi_fixedIBC
      real(kind=8) id_tov_depletion
      real(kind=8) id_tovbh_vx
      real(kind=8) id_tovbh_vy
      real(kind=8) id_tovbh_vz
      integer id_tov_average
      real(kind=8) id_tov_p_pres
      real(kind=8) id_tov_p_r
      real(kind=8) id_tov_p_sigma
      integer id_tov_magnetic
      real(kind=8) id_tov_Asize
      real(kind=8) id_drns_r_e
      real(kind=8) id_center_x1
      real(kind=8) id_center_y1
      real(kind=8) id_center_x2
      real(kind=8) id_center_y2
      real(kind=8) id_vx1
      real(kind=8) id_vy1
      real(kind=8) id_vx2
      real(kind=8) id_vy2
      integer id_perturb_m
      real(kind=8) id_perturb_p
      real(kind=8) id_perturb_rho
      real(kind=8) id_disk_width
      real(kind=8) id_disk_rin
      real(kind=8) id_disk_rout
      real(kind=8) id_disk_B
      integer id_disk_type
      real(kind=8) id_disk_angmom
      real(kind=8) id_disk_potential
      real(kind=8) id_disk_atmosphere
      real(kind=8) id_disk_kappa
      real(kind=8) id_disk_Asize
      real(kind=8) id_disk_rhocut
      integer id_disk_magnetic
      real(kind=8) id_disk_rho0
      real(kind=8) id_disk_decay
      real(kind=8) id_disk_kickvel
      real(kind=8) id_disk_kicktheta
      real(kind=8) id_disk_kickphi
      real(kind=8) id_disk_GammaB
      real(kind=8) id_disk_cB
      real(kind=8) id_disk_lbound
      real(kind=8) id_disk_bhmass
      integer nx0
      integer ny0
      integer nz0
      integer nt0
      real(kind=8) h
      real(kind=8) hx
      real(kind=8) hy
      real(kind=8) hz
      real(kind=8) hxyz0
      real(kind=8) run_wtime
      real(kind=8) amp
      integer idata
      real(kind=8) maxchi_thresh
      real(kind=8) maxchi_minctime
      integer local_nx
      integer local_ny
      integer local_nz
      integer global_nx
      integer global_ny
      integer global_nz
      integer local_lower_bnd_x
      integer local_lower_bnd_y
      integer local_lower_bnd_z
      integer bbox1
      integer bbox2
      integer bbox3
      integer bbox4
      integer bbox5
      integer bbox6
      integer nghostzones_x
      integer nghostzones_y
      integer nghostzones_z
      real(kind=8) dt
      real(kind=8) dx
      real(kind=8) dy
      real(kind=8) dz
      real(kind=8) local_time
      integer alt_coord_type
      real(kind=8) pc_coord_trans_rad
      real(kind=8) pc_coord_trans_width
      real(kind=8) pc_coord_scale
      integer bc_type
      integer inner_bound_data
      integer deriv_order
      integer dissipation
      real(kind=8) sigma_diss
      real(kind=8) extradiss
      real(kind=8) extradissOUT
      integer nbholes
      integer use_mask
      integer mask_type
      integer initial_analysis
      real(kind=8) bh1_mass
      real(kind=8) bh1_spin
      real(kind=8) bh1_spin_phi
      real(kind=8) bh1_spin_theta
      real(kind=8) bh1_x0
      real(kind=8) bh1_y0
      real(kind=8) bh1_z0
      real(kind=8) bh1_vx
      real(kind=8) bh1_vy
      real(kind=8) bh1_exc_rad
      real(kind=8) bh1_velx
      real(kind=8) bh2_mass
      real(kind=8) bh2_spin
      real(kind=8) bh2_spin_phi
      real(kind=8) bh2_spin_theta
      real(kind=8) bh2_x0
      real(kind=8) bh2_y0
      real(kind=8) bh2_z0
      real(kind=8) bh2_exc_rad
      real(kind=8) bh2_velx
      integer boundary_conditions
      real(kind=8) penalty
      integer PP
      integer QQ
      real(kind=8) t0
      real(kind=8) sigma_t
      real(kind=8) amp_boundary
      real(kind=8) amp_random_bc
      real(kind=8) sigma_rho
      integer interp_id
      integer runge_kutta_type
      integer runge_kutta_bound
      integer point_wise_analysis
      integer psi4_analysis
      integer rk_iter
      integer asf_ntheta
      integer asf_nphi
      integer asf_period
      integer asf_level
      real(kind=8) asf_rconst
      integer bsf_ntheta
      integer bsf_nphi
      integer bsf_period
      integer bsf_level
      real(kind=8) bsf_rconst
      integer csf_ntheta
      integer csf_nphi
      integer csf_period
      integer csf_level
      real(kind=8) csf_rconst
      common / use_params / mr_amp,mr_shift,bamp,e1_amp,e2_amp,sf_amp,sf
     &_amp_axn,dil_mass,dil_alpha,dil_infty,axn_mass,axn_alpha,axn_infty
     &,sen_alpha,a_ang_par,q_elec,p_mag,bs_1_x0,bs_1_y0,bs_1_z0,bs_1_vx,
     &bs_1_vy,bs_1_vz,bs_1_omega,bs_2_x0,bs_2_y0,bs_2_z0,bs_2_vx,bs_2_vy
     &,bs_2_vz,bs_2_omega,bh_1_mass,bh_2_mass,bh_3_mass,bh_4_mass,bh_1_x
     &,bh_1_y,bh_1_z,bh_2_x,bh_2_y,bh_2_z,bh_3_x,bh_3_y,bh_3_z,bh_4_x,bh
     &_4_y,bh_4_z,bh_1_px,bh_1_py,bh_1_pz,bh_2_px,bh_2_py,bh_2_pz,bh_3_p
     &x,bh_3_py,bh_3_pz,bh_4_px,bh_4_py,bh_4_pz,bh_1_spin,bh_1_sth,bh_1_
     &sphi,bh_2_spin,bh_2_sth,bh_2_sphi,bh_3_spin,bh_3_sth,bh_3_sphi,bh_
     &4_spin,bh_4_sth,bh_4_sphi,outer_boundary,gr_bound_cond,fluid_bound
     &_cond,bssn_lambda_f0,bssn_lambda_f1,bssn_lambda_f2,bssn_lambda_f3,
     &bssn_eta_damping,bssn_R_0,bssn_eta_damping_exp,bssn_eta,bssn_trk0,
     &bssn_kappa1,bssn_kappa2,bssn_chi_floor,q1,vinj,Kappajan,djump,rpea
     &k,rout,stab,rho_real,magcase,kappa_max,G_scale_factor,B_scale_fact
     &or,bfield_taperrange,psi_ch,psi_cr,id_bondi_sonic_r,id_bondi_rhoc,
     &id_bondi_rstart,id_tov_depletion,id_tovbh_vx,id_tovbh_vy,id_tovbh_
     &vz,id_tov_p_pres,id_tov_p_r,id_tov_p_sigma,id_tov_Asize,id_drns_r_
     &e,id_center_x1,id_center_y1,id_center_x2,id_center_y2,id_vx1,id_vy
     &1,id_vx2,id_vy2,id_perturb_p,id_perturb_rho,id_disk_width,id_disk_
     &rin,id_disk_rout,id_disk_B,id_disk_angmom,id_disk_potential,id_dis
     &k_atmosphere,id_disk_kappa,id_disk_Asize,id_disk_rhocut,id_disk_rh
     &o0,id_disk_decay,id_disk_kickvel,id_disk_kicktheta,id_disk_kickphi
     &,id_disk_GammaB,id_disk_cB,id_disk_lbound,id_disk_bhmass,h,hx,hy,h
     &z,hxyz0,run_wtime,amp,maxchi_thresh,maxchi_minctime,dt,dx,dy,dz,lo
     &cal_time,pc_coord_trans_rad,pc_coord_trans_width,pc_coord_scale,si
     &gma_diss,extradiss,extradissOUT,bh1_mass,bh1_spin,bh1_spin_phi,bh1
     &_spin_theta,bh1_x0,bh1_y0,bh1_z0,bh1_vx,bh1_vy,bh1_exc_rad,bh1_vel
     &x,bh2_mass,bh2_spin,bh2_spin_phi,bh2_spin_theta,bh2_x0,bh2_y0,bh2_
     &z0,bh2_exc_rad,bh2_velx,penalty,t0,sigma_t,amp_boundary,amp_random
     &_bc,sigma_rho,asf_rconst,bsf_rconst,csf_rconst,gauge_type,idtype,e
     &volve_geometry,evolve_em_field,evolve_scalar_field,temperature_typ
     &e,read_file_alp,read_file_b,read_file_g,read_file_k,read_file_psi,
     &read_file_phir,read_file_phic,read_file_phim,read_data_level,id_d_
     &diff_order,initial_b,initial_sf,emd_bh_type,bh_n,bh_type,bssn_lamb
     &da_1,bssn_lambda_2,bssn_lambda_3,bssn_lambda_4,bssn_adv_derivs,geo
     &metry_type,gr_idtype,mhd_idtype,detgwarn,force_free,calcDivB,const
     &raints_analysis,anti_aligned,bfield_vacuumfreeze,project_div_B,dam
     &p,id_bondi_fixedIBC,id_tov_average,id_tov_magnetic,id_perturb_m,id
     &_disk_type,id_disk_magnetic,nx0,ny0,nz0,nt0,idata,local_nx,local_n
     &y,local_nz,global_nx,global_ny,global_nz,local_lower_bnd_x,local_l
     &ower_bnd_y,local_lower_bnd_z,bbox1,bbox2,bbox3,bbox4,bbox5,bbox6,n
     &ghostzones_x,nghostzones_y,nghostzones_z,alt_coord_type,bc_type,in
     &ner_bound_data,deriv_order,dissipation,nbholes,use_mask,mask_type,
     &initial_analysis,boundary_conditions,PP,QQ,interp_id,runge_kutta_t
     &ype,runge_kutta_bound,point_wise_analysis,psi4_analysis,rk_iter,as
     &f_ntheta,asf_nphi,asf_period,asf_level,bsf_ntheta,bsf_nphi,bsf_per
     &iod,bsf_level,csf_ntheta,csf_nphi,csf_period,csf_level
